[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.5"
indicatif = "0.16.2"
rayon = "1.5.2"
itertools = "0.10.3"
dyn-clone = "1.0.5"